// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Todo struct {
	TodoID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Label     string
	Completed bool
}
