// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: todos.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTodo = `-- name: CreateTodo :one

INSERT INTO todos (todo_id, created_at, updated_at, label, completed)
VALUES ($1, $2, $3, $4, $5)
RETURNING todo_id, created_at, updated_at, label, completed
`

type CreateTodoParams struct {
	TodoID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Label     string
	Completed bool
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.TodoID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Label,
		arg.Completed,
	)
	var i Todo
	err := row.Scan(
		&i.TodoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.Completed,
	)
	return i, err
}
