// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ReportsReport struct {
	ReportID            uuid.UUID      `json:"report_id"`
	OwnerUserID         string         `json:"owner_user_id"`
	ReportType          string         `json:"report_type"`
	Status              string         `json:"status"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	StartedAt           sql.NullTime   `json:"started_at"`
	CompletedAt         sql.NullTime   `json:"completed_at"`
	FailureReason       sql.NullString `json:"failure_reason"`
	Result              sql.NullString `json:"result"`
	ProcessingStartedAt sql.NullTime   `json:"processing_started_at"`
	FailureCode         sql.NullString `json:"failure_code"`
}
