// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const claimReportExecution = `-- name: ClaimReportExecution :one
UPDATE reports.reports
SET status = 'processing',
    processing_started_at = $1,
    updated_at = $1,
    started_at = COALESCE(started_at, $1),
    failure_reason = NULL,
    failure_code = NULL
WHERE report_id = $2
  AND (
    status = 'pending'
    OR (status = 'processing' AND (processing_started_at IS NULL OR processing_started_at < $3))
  )
RETURNING report_id, owner_user_id, report_type, status, created_at, updated_at, started_at, completed_at, failure_reason, result, processing_started_at, failure_code
`

type ClaimReportExecutionParams struct {
	NowAt       sql.NullTime `json:"now_at"`
	ReportID    uuid.UUID    `json:"report_id"`
	StaleBefore sql.NullTime `json:"stale_before"`
}

func (q *Queries) ClaimReportExecution(ctx context.Context, arg ClaimReportExecutionParams) (ReportsReport, error) {
	row := q.db.QueryRowContext(ctx, claimReportExecution, arg.NowAt, arg.ReportID, arg.StaleBefore)
	var i ReportsReport
	err := row.Scan(
		&i.ReportID,
		&i.OwnerUserID,
		&i.ReportType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.Result,
		&i.ProcessingStartedAt,
		&i.FailureCode,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports.reports (
    report_id, owner_user_id, report_type, status,
    created_at, updated_at, started_at, completed_at,
    processing_started_at, failure_reason, failure_code, result
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING report_id, owner_user_id, report_type, status, created_at, updated_at, started_at, completed_at, failure_reason, result, processing_started_at, failure_code
`

type CreateReportParams struct {
	ReportID            uuid.UUID      `json:"report_id"`
	OwnerUserID         string         `json:"owner_user_id"`
	ReportType          string         `json:"report_type"`
	Status              string         `json:"status"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	StartedAt           sql.NullTime   `json:"started_at"`
	CompletedAt         sql.NullTime   `json:"completed_at"`
	ProcessingStartedAt sql.NullTime   `json:"processing_started_at"`
	FailureReason       sql.NullString `json:"failure_reason"`
	FailureCode         sql.NullString `json:"failure_code"`
	Result              sql.NullString `json:"result"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (ReportsReport, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ReportID,
		arg.OwnerUserID,
		arg.ReportType,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ProcessingStartedAt,
		arg.FailureReason,
		arg.FailureCode,
		arg.Result,
	)
	var i ReportsReport
	err := row.Scan(
		&i.ReportID,
		&i.OwnerUserID,
		&i.ReportType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.Result,
		&i.ProcessingStartedAt,
		&i.FailureCode,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT report_id, owner_user_id, report_type, status, created_at, updated_at, started_at, completed_at, failure_reason, result, processing_started_at, failure_code FROM reports.reports WHERE report_id = $1 LIMIT 1
`

func (q *Queries) GetReportByID(ctx context.Context, reportID uuid.UUID) (ReportsReport, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, reportID)
	var i ReportsReport
	err := row.Scan(
		&i.ReportID,
		&i.OwnerUserID,
		&i.ReportType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.Result,
		&i.ProcessingStartedAt,
		&i.FailureCode,
	)
	return i, err
}

const listPendingReportsOlderThan = `-- name: ListPendingReportsOlderThan :many
SELECT report_id, owner_user_id, report_type, status, created_at, updated_at, started_at, completed_at, failure_reason, result, processing_started_at, failure_code FROM reports.reports
WHERE status = 'pending'
  AND updated_at < $1
ORDER BY updated_at ASC
`

func (q *Queries) ListPendingReportsOlderThan(ctx context.Context, updatedBefore time.Time) ([]ReportsReport, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReportsOlderThan, updatedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportsReport
	for rows.Next() {
		var i ReportsReport
		if err := rows.Scan(
			&i.ReportID,
			&i.OwnerUserID,
			&i.ReportType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureReason,
			&i.Result,
			&i.ProcessingStartedAt,
			&i.FailureCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByOwner = `-- name: ListReportsByOwner :many
SELECT report_id, owner_user_id, report_type, status, created_at, updated_at, started_at, completed_at, failure_reason, result, processing_started_at, failure_code FROM reports.reports
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReportsByOwner(ctx context.Context, ownerUserID string) ([]ReportsReport, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportsReport
	for rows.Next() {
		var i ReportsReport
		if err := rows.Scan(
			&i.ReportID,
			&i.OwnerUserID,
			&i.ReportType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureReason,
			&i.Result,
			&i.ProcessingStartedAt,
			&i.FailureCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportCompleted = `-- name: MarkReportCompleted :one
UPDATE reports.reports
SET status = 'completed',
    result = $1,
    completed_at = $2,
    updated_at = $2,
    processing_started_at = NULL,
    failure_reason = NULL,
    failure_code = NULL
WHERE report_id = $3
  AND status = 'processing'
RETURNING report_id, owner_user_id, report_type, status, created_at, updated_at, started_at, completed_at, failure_reason, result, processing_started_at, failure_code
`

type MarkReportCompletedParams struct {
	Result   sql.NullString `json:"result"`
	NowAt    sql.NullTime   `json:"now_at"`
	ReportID uuid.UUID      `json:"report_id"`
}

func (q *Queries) MarkReportCompleted(ctx context.Context, arg MarkReportCompletedParams) (ReportsReport, error) {
	row := q.db.QueryRowContext(ctx, markReportCompleted, arg.Result, arg.NowAt, arg.ReportID)
	var i ReportsReport
	err := row.Scan(
		&i.ReportID,
		&i.OwnerUserID,
		&i.ReportType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.Result,
		&i.ProcessingStartedAt,
		&i.FailureCode,
	)
	return i, err
}

const markReportFailed = `-- name: MarkReportFailed :one
UPDATE reports.reports
SET status = 'failed',
    failure_reason = $1,
    failure_code = $2,
    completed_at = $3,
    updated_at = $3,
    processing_started_at = NULL
WHERE report_id = $4
  AND status = 'processing'
RETURNING report_id, owner_user_id, report_type, status, created_at, updated_at, started_at, completed_at, failure_reason, result, processing_started_at, failure_code
`

type MarkReportFailedParams struct {
	FailureReason sql.NullString `json:"failure_reason"`
	FailureCode   sql.NullString `json:"failure_code"`
	NowAt         sql.NullTime   `json:"now_at"`
	ReportID      uuid.UUID      `json:"report_id"`
}

func (q *Queries) MarkReportFailed(ctx context.Context, arg MarkReportFailedParams) (ReportsReport, error) {
	row := q.db.QueryRowContext(ctx, markReportFailed,
		arg.FailureReason,
		arg.FailureCode,
		arg.NowAt,
		arg.ReportID,
	)
	var i ReportsReport
	err := row.Scan(
		&i.ReportID,
		&i.OwnerUserID,
		&i.ReportType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.Result,
		&i.ProcessingStartedAt,
		&i.FailureCode,
	)
	return i, err
}

const markReportPendingRetry = `-- name: MarkReportPendingRetry :one
UPDATE reports.reports
SET status = 'pending',
    processing_started_at = NULL,
    updated_at = $1,
    failure_reason = NULL,
    failure_code = NULL
WHERE report_id = $2
  AND status = 'processing'
RETURNING report_id, owner_user_id, report_type, status, created_at, updated_at, started_at, completed_at, failure_reason, result, processing_started_at, failure_code
`

type MarkReportPendingRetryParams struct {
	NowAt    time.Time `json:"now_at"`
	ReportID uuid.UUID `json:"report_id"`
}

func (q *Queries) MarkReportPendingRetry(ctx context.Context, arg MarkReportPendingRetryParams) (ReportsReport, error) {
	row := q.db.QueryRowContext(ctx, markReportPendingRetry, arg.NowAt, arg.ReportID)
	var i ReportsReport
	err := row.Scan(
		&i.ReportID,
		&i.OwnerUserID,
		&i.ReportType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureReason,
		&i.Result,
		&i.ProcessingStartedAt,
		&i.FailureCode,
	)
	return i, err
}
