// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO auth.api_tokens (token_id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING token_id, user_id, token_hash, expires_at, created_at
`

type CreateAPITokenParams struct {
	TokenID   uuid.UUID `json:"token_id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (AuthApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.TokenID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AuthApiToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth.sessions (session_id, user_id, expires_at, created_at)
VALUES ($1, $2, $3, $4)
RETURNING session_id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.SessionID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (user_id, email, password_hash, roles, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING user_id, email, password_hash, roles, created_at
`

type CreateUserParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Roles        []string  `json:"roles"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.PasswordHash,
		pq.Array(arg.Roles),
		arg.CreatedAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		pq.Array(&i.Roles),
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM auth.api_tokens WHERE token_id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, tokenID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAPIToken, tokenID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth.sessions WHERE session_id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT token_id, user_id, token_hash, expires_at, created_at FROM auth.api_tokens WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (AuthApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i AuthApiToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT session_id, user_id, expires_at, created_at FROM auth.sessions WHERE session_id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, sessionID uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionID)
	var i AuthSession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, password_hash, roles, created_at FROM auth.users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		pq.Array(&i.Roles),
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, email, password_hash, roles, created_at FROM auth.users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i AuthUser
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		pq.Array(&i.Roles),
		&i.CreatedAt,
	)
	return i, err
}
