// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTodos = `-- name: CountTodos :one
SELECT
    COUNT(*)::bigint AS total,
    COUNT(*) FILTER (WHERE completed)::bigint AS completed
FROM todos.todos
`

type CountTodosRow struct {
	Total     int64 `json:"total"`
	Completed int64 `json:"completed"`
}

func (q *Queries) CountTodos(ctx context.Context) (CountTodosRow, error) {
	row := q.db.QueryRowContext(ctx, countTodos)
	var i CountTodosRow
	err := row.Scan(&i.Total, &i.Completed)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos.todos (todo_id, created_at, updated_at, label, completed)
VALUES ($1, $2, $3, $4, $5)
RETURNING todo_id, created_at, updated_at, label, completed
`

type CreateTodoParams struct {
	TodoID    uuid.UUID `json:"todo_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Label     string    `json:"label"`
	Completed bool      `json:"completed"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (TodosTodo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.TodoID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Label,
		arg.Completed,
	)
	var i TodosTodo
	err := row.Scan(
		&i.TodoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.Completed,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos.todos WHERE todo_id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, todoID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, todoID)
	return err
}

const findTodoById = `-- name: FindTodoById :one
SELECT todo_id, created_at, updated_at, label, completed FROM todos.todos WHERE todo_id = $1 LIMIT 1
`

func (q *Queries) FindTodoById(ctx context.Context, todoID uuid.UUID) (TodosTodo, error) {
	row := q.db.QueryRowContext(ctx, findTodoById, todoID)
	var i TodosTodo
	err := row.Scan(
		&i.TodoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.Completed,
	)
	return i, err
}

const listAllTodos = `-- name: ListAllTodos :many
SELECT todo_id, created_at, updated_at, label, completed FROM todos.todos ORDER BY created_at DESC
`

func (q *Queries) ListAllTodos(ctx context.Context) ([]TodosTodo, error) {
	rows, err := q.db.QueryContext(ctx, listAllTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodosTodo
	for rows.Next() {
		var i TodosTodo
		if err := rows.Scan(
			&i.TodoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Label,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos.todos
SET updated_at = $2, label = $3, completed = $4
WHERE todo_id = $1
RETURNING todo_id, created_at, updated_at, label, completed
`

type UpdateTodoParams struct {
	TodoID    uuid.UUID `json:"todo_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Label     string    `json:"label"`
	Completed bool      `json:"completed"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (TodosTodo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.TodoID,
		arg.UpdatedAt,
		arg.Label,
		arg.Completed,
	)
	var i TodosTodo
	err := row.Scan(
		&i.TodoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.Completed,
	)
	return i, err
}
